name: Auto lint when pull request

on:
	pull_request:
		branches:
			- main

jobs:
	test:
		runs-on: ubuntu-lastest

	env:
		MODE: "dev"

	steps:
		- uses: actions/checkout@v3
		
		- name: Install dependencies
		  run: npm install -f

		- name: Lint and format code
		  run: npx lint