name: Auto lint when pull request

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    env:
      MODE: "dev"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install -f

      - name: Lint and format code
        run: npm run lint